export const GET_TASKS = "GET_TASKS"
export const REMOVE_TASK = "REMOVE_TASK"
export const TOGGLE_TASK_REMINDER = "TOGGLE_TASK_REMINDER"
export const SET_NEW_TASK = "SET_NEW_TASK"

// FORM
export const SET_TASK = "SET_TASK"
export const SET_TASK_DATE_TIME = "SET_TASK_DATE_TIME"
export const SET_TASK_REMINDER = "SET_TASK_REMINDER"